[phases.setup]
nixPkgs = ["nodejs_18", "git", "git-lfs"]

[phases.install]
cmds = [
  "git --version",
  "git lfs version",
  "git lfs install",
  "git lfs fetch --all",
  "git lfs checkout",
  "ls -lh Build/deployment_1_1.wasm",
  "head -c 4 Build/deployment_1_1.wasm | od -A x -t x1z -v",
  "npm ci --omit=dev"
]

[start]
cmd = "npm start"
