[phases.setup]
nixPkgs = ["nodejs_18", "curl"]

[phases.install]
cmds = [
  "echo 'Downloading LFS files during build with parallel downloads...'",
  "curl --retry 10 --retry-delay 3 --retry-all-errors --connect-timeout 120 --max-time 900 --compressed -# -L -o Build/deployment_1_1.wasm https://media.githubusercontent.com/media/hafizhuzaifaahmed/unity-webgl-app-test-2/main/Build/deployment_1_1.wasm &",
  "curl --retry 10 --retry-delay 3 --retry-all-errors --connect-timeout 120 --max-time 900 --compressed -# -L -o Build/deployment_1_1.data https://media.githubusercontent.com/media/hafizhuzaifaahmed/unity-webgl-app-test-2/main/Build/deployment_1_1.data &",
  "wait",
  "ls -lh Build/deployment_1_1.wasm Build/deployment_1_1.data",
  "head -c 4 Build/deployment_1_1.wasm | od -A x -t x1z -v",
  "npm ci --omit=dev"
]

[start]
cmd = "npm start"
