[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

# Railway resource optimization
# Increase memory for better caching and faster file serving
[[deploy.healthcheck]]
path = "/"
timeout = 300
interval = 60
